{
 "title": "Devops Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "BUSINESS OVERVIEW (CUMULATIVE)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Successful Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(shop_orders_total{status=\"success\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Failed Orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(shop_orders_total{status=\"failed\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "REAL-TIME SERVICE HEALTH (MATCHES ALERTS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Average Latency (Alert Threshold: 1s)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((sum(rate(http_request_latency_seconds_sum[1m])) / sum(rate(http_request_latency_seconds_count[1m]))) >= 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Order Failure Rate (Alert Threshold: 15%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((sum(rate(shop_orders_total{status=\"failed\"}[1m])) / sum(rate(shop_orders_total[1m]))) >= 0) or vector(0)"
    }
   ]
  },
  { "title": "TRAFFIC ANALYSIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Order Throughput Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "rate(shop_orders_total[1m])", "legendFormat": "Status: {{status}}" }
   ]
  }
 ]
}